In [2]:
import numpy as np

### Array creation

In [3]:
npm_array_0=np.array(42)
np_array_1d=np.array([1,2,3])
np_array_2d=np.array([[1,2,3],[4,5,6]])
np_array_3d=np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(npm_array_0)
print(np_array_1d)
print(np_array_2d)
print(np_array_3d)


42
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### List vs np arr

In [4]:
list1=[1,2,3]
np_arr=np.array([1,2,3])*2

print(list1*2)
print(np_arr)

[1, 2, 3, 1, 2, 3]
[2 4 6]


### Array types

In [5]:
zeros = np.zeros((3,3))
ones = np.ones((3,3))
full = np.full((3,3), 7)
random = np.random.random((3,3))
seq= np.arange(0, 30, 5)
seq

array([ 0,  5, 10, 15, 20, 25])

### Vector, Matrix, Tensor 

In [6]:
vector = np.array([1, 2, 3])
matrix = np.array([[1,2],[3,4]])
tensor= np.array([[[1,2],[3,4]],
                  [[5,6],[7,8]]])
tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### Props

In [7]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print("Shape : " , arr.shape)
print("Dimension : " , arr.ndim)
print("Len : ", arr.size)
print("Data type : " , arr.dtype)


Shape :  (3, 3)
Dimension :  2
Len :  9
Data type :  int64


### Array Reshaping

In [8]:
arr= np.arange(12)

arr1= arr.reshape((3,4))

arr2 = arr1.flatten()

arr3=arr1.ravel()

# Transpose-------------

arr4=arr1.transpose()
# arr4=arr1.T
# print(arr1)
print(arr4[0][])


[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [196]:
arr=np.arange(11)
a=np.hstack((arr,[2]))
np.delete(a,2)

array([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10,  2])